#!/bin/bash

txtred="\033[0;31m"       # red
txtgrn="\033[0;32m"       # green
txtrst="\033[0m"          # Text reset

# Get the absolute path of the executable
function realpath {
    local r=$1; local t=$(readlink $r)
    while [ $t ]; do
        r=$(cd $(dirname $r) && cd $(dirname $t) && pwd -P)/$(basename $t)
        t=$(readlink $r)
    done
    echo $r
}
AV_INSTALLED_PATH=$(dirname $(realpath "$0"))

# Figure out where the .av directory is starting with pwd
upsearch () {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  topdir="`cd ~/;pwd`"
  for (( n=${#slashes}; n>0; --n ))
  do
	if [[ $directory == $topdir ]]; then
		return
	fi
    test -e "$directory/$1" && export AV_ROOT="$directory/$1" && return
	directory="`cd "$directory/..";pwd`"
  done
}

# --------------------------------------------------------------------

# Built-in commands
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	export AV_CONFIG_DIR=$AV_INSTALLED_PATH/config
	cd $AV_INSTALLED_PATH/config && ./welcome
	echo
	echo "Flags: "
	echo "  --help      - this helpful display"
	echo 
	echo "Commands that work on the current directory: "
	echo "  init        - creates a new domain specific shell in your current path"
	echo "  status      - displays 'av' if a domain specific shell is in your current path"
	echo "  get         - install plugin from repository"
	echo "  invigorate  - checks your domain specific shell's version and imposes the changes necessary"
	echo "  upgrade     - pull updates for av-shell and plugins, system wide"
	echo "  update      - same as upgrade"
	echo
	exit
fi


if [[ "$1" == "init" && -z "$AV_ROOT" ]]; then
	echo "This utility creates a new domain specific shell in your current path"
	echo

    if [[ -e .av ]]; then
    	echo "It appears 'av' is already installed"
    	exit
    fi

	echo "your prompt should be named?:"
	read prompt

	echo
	echo "copying files..."
	mkdir .av
	mkdir .av/bin
	mkdir .av/config
	touch .av/config/.gitignore
	echo "vars/container" >> .av/config/.gitignore
    echo "vars/cluster" >> .av/config/.gitignore
    echo "vars/branch" >> .av/config/.gitignore
    echo "vars/cluster_type" >> .av/config/.gitignore
    echo "vars/profile" >> .av/config/.gitignore
	echo "vars/lasthash" >> .av/config/.gitignore
	echo "$prompt" > .av/config/prompt

	echo
	echo "done"

	exit
fi

if [[ "$1" == "get" && -z "$AV_ROOT" ]]; then

	if [[ $# -ne 2 ]]; then
		echo "Usage: av get <repository>"
		exit 1
	fi

  reponame="$(basename "${2%.*}")"
  if [[ -e ~/.av/plugins/${reponame} ]]; then
		echo -e "${txtgrn}[AV-SHELL]${txtrst} Plugin already installed, pulling latest"
		cd ~/.av/plugins/${reponame} && git pull
	else
		cd ~/.av/plugins && git clone $2
	fi

	exit
fi

# See if there is an .av directory
upsearch ".av"


if [[ "$1" == "status" ]]; then
	if [[ ! -z $AV_ROOT ]]; then
		echo -n "av"
	fi
	exit
fi

if [[ -z "$AV_ROOT" && $# -eq 0 ]]; then
	echo "Unable to find av environment, have you run 'av init'?"
	exit
fi

# --------------------------------------------------------------------

# Change dir to script root
cd $AV_ROOT/.. > /dev/null

# Support dotenv
if [[ -f .env ]]; then
	unamestr=$(uname)
	if [ "$unamestr" = 'Linux' ]; then

	export $(grep -v '^#' .env | xargs -d '\n')

	elif [[ "$unamestr" = 'FreeBSD' || "$unamestr" = 'Darwin' ]]; then

	export $(grep -v '^#' .env | xargs -0)

	fi
fi

# If there are arguments, just run them rather than opening a shell
if [ $# -eq 0 ]; then

	FORCED_COMMAND=""
	if [ -e $AV_ROOT/config/version ]; then

		echo -en "${txtgrn}[AV-SHELL]${txtred} Your local .av folder can be simplified...do so now? [Y/n]: ${txtrst}"
		read prompt
		if [[ "$prompt" != "n" && "$prompt" != "N" ]]; then
			AV_INSTALLED_PATH=$AV_INSTALLED_PATH AV_NON_INTERACTIVE=true AV_ROOT=$AV_ROOT PATH=$AV_ROOT/bin:$PATH ZDOTDIR=$AV_INSTALLED_PATH/config zsh -i -c invigorate
		fi
	else
		CURRENT_DATE=`date +%s`
		if [[ ! -e $AV_INSTALLED_PATH/config/update_checked ]]; then
			echo "${CURRENT_DATE}" > $AV_INSTALLED_PATH/config/update_checked
		else
			LAST_CHECKED=`cat $AV_INSTALLED_PATH/config/update_checked`
			if [[ `expr ${CURRENT_DATE} - ${LAST_CHECKED}` -gt 1728000 ]]; then
				echo -en "${txtred}[AV-SHELL]${txtgrn} Would you like to check for updates? [Y/n]: ${txtrst}"
				read prompt
				echo "${CURRENT_DATE}" > $AV_INSTALLED_PATH/config/update_checked
				if [[ "$prompt" != "n" && "$prompt" != "N" ]]; then
					AV_INSTALLED_PATH=$AV_INSTALLED_PATH AV_NON_INTERACTIVE=true AV_ROOT=$AV_ROOT PATH=$AV_ROOT/bin:$PATH ZDOTDIR=$AV_INSTALLED_PATH/config zsh -i -c upgrade
				fi
			fi
		fi
	fi

	# Open shell
	AV_INSTALLED_PATH=$AV_INSTALLED_PATH AV_ROOT=$AV_ROOT ZDOTDIR=$AV_INSTALLED_PATH/config zsh ${FORCED_COMMAND}

else

	# Run command in shell
	AV_INSTALLED_PATH=$AV_INSTALLED_PATH AV_NON_INTERACTIVE=true AV_ROOT=$AV_ROOT PATH=$AV_ROOT/bin:$PATH ZDOTDIR=$AV_INSTALLED_PATH/config zsh -i -c "$*"
  exit $?

fi

# Go back
cd - > /dev/null
