#! /bin/bash

# Get to the root of av-shell install
cd $(dirname "$0")

# Import color
source config/color
av_shell_prompt="${txtblu}[AV-SHELL]${txtrst}"

# Error Check
function error_check {
    if [[ $1 == 0 ]]; then
        echo -e " - ${txtgrn}success${txtrst}"
    else
        echo -e " - ${txtred}failed${txtrst}"
    fi
}

# Check for brew and install dependencies
if [[ -z "$(which brew)" ]]; then
    echo "${av_shell_prompt} Brew must be installed to ensure dependencies are fulfilled, "
    echo
    echo "Run the following command and retry"
    echo
    echo "/bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
    echo
    exit 1
fi
brew install jq gum k9s octant dive

# Check for golang
go_path=`which go`
if [[ -z "${go_path}" ]]; then
    echo -e "${av_shell_prompt} ${txtred}Unable to find golang which is required for install...try again${txtrst}"
    exit 1
fi
go install github.com/erning/gorun@latest

INSTALL_DIR="$HOME/.local/bin"
echo -en "${av_shell_prompt} Creating symlink in ${txtpur}${INSTALL_DIR}${txtrst}"
rm -f ${INSTALL_DIR}/av > /dev/null 2>&1
ln -s `pwd`/av ${INSTALL_DIR}/av > /dev/null 2>&1
if [[ $? != 0 && -z $1 ]]; then
    error_check $?
else
    echo -e " - ${txtgrn}success${txtrst}"
fi
