#! /bin/bash

# Get to the root of av-shell install
cd $(dirname "$0")

# Import color
source config/color

# Verify osx
if [[ "$OSTYPE" != "darwin"* && `whoami` != "root" && $1 != "--user" ]]; then
    echo -e "${txtgrn}[AV-SHELL]${txtrst} install must be run as ${txtred}root${txtrst} on your system, re-running..."
    sudo bash ./install
    exit $?
fi

echo -e "${txtgrn}[AV-SHELL]${txtrst} Creating symlink in ${txtpur}/usr/local/bin${txtrst}"
rm -f /usr/local/bin/av > /dev/null
ln -s `pwd`/av /usr/local/bin/av

echo -e "${txtgrn}[AV-SHELL]${txtrst} Building ${txtpur}prompts/menu${txtrst} system"
cd plugins/av-prompts && make; cd ../..
cd plugins/av-clusters && make; cd ../..
cd plugins/yamlmerge && make; cd ../..
