#!/bin/bash

if [[ $1 == "" ]]; then
    echo "Usage: $0 <version>"
    exit
fi

cd ..
make linux  -C .av/plugins/av-prompts
tar -c --exclude .git --exclude .idea -z -f av-shell-$1-linux64.tar.gz .av
make -C .av/plugins/av-prompts
tar -c --exclude .git --exclude .idea -z -f av-shell-$1-mac.tar.gz .av
mv av-shell-$1-* .av
cd -