#!/bin/bash

if [[ $1 == "" ]]; then
    echo "Usage: $0 <version>"
    exit
fi

excludes="--exclude=**/*.gz --exclude=**/.vscode --exclude=**/.idea --exclude=**/.DS_Store --exclude=**/.git --exclude=**/.zcompdump --exclude=**/.zsh_history"
cd ..

# Linux
make linux -C .av/plugins/av-prompts
make -C .av/plugins/yamlmerge
tar ${excludes} -c -z -f av-shell-$1-linux64.tar.gz .av
echo
echo -e "----------------------------------------------------------"
echo -e "|   Produced: av-shell-$1-linux64.tar.gz"
echo -e "----------------------------------------------------------"
echo

# OSX
make -C .av/plugins/av-prompts
make -C .av/plugins/yamlmerge
tar ${excludes} -c -z -f av-shell-$1-mac.tar.gz .av
echo
echo -e "----------------------------------------------------------"
echo -e "|   Produced: av-shell-$1-mac.tar.gz"
echo -e "----------------------------------------------------------"
echo

# Move into .av folder
mv av-shell-$1-* .av
cd -