#!/bin/bash

if [[ $1 == "" ]]; then
    echo "Usage: $0 <version>"
    exit
fi

excludes='--exclude .git --exclude .idea'
cd ..

# Linux
make linux -C .av/plugins/av-prompts
make linux -C .av/plugins/configgen
tar -c ${excludes} -z -f av-shell-$1-linux64.tar.gz .av
echo -e "Produced: av-shell-$1-linux64.tar.gz"

# OSX
make -C .av/plugins/av-prompts
make -C .av/plugins/configgen
tar -c ${excludes} -z -f av-shell-$1-mac.tar.gz .av
echo -e "Produced: av-shell-$1-linux64.tar.gz"

# Move into .av folder
mv av-shell-$1-* .av
cd -