#!/bin/bash

# Text color variables
txtred="\033[0;31m"       # red
txtgrn="\033[0;32m"       # green
txtylw="\033[0;33m"       # yellow
txtblu="\033[0;34m"       # blue
txtpur="\033[0;35m"       # purple
txtcyn="\033[0;36m"       # cyan
txtwht="\033[0;37m"       # white
bldred="\033[1;31m"       # red    - Bold
bldgrn="\033[1;32m"       # green
bldylw="\033[1;33m"       # yellow
bldblu="\033[1;34m"       # blue
bldpur="\033[1;35m"       # purple
bldcyn="\033[1;36m"       # cyan
bldwht="\033[1;37m"       # white
txtrst="\033[0m"          # Text reset
 
# Feedback indicators
info=${bldwht}*${txtrst}
pass=${bldblu}*${txtrst}
warn=${bldred}!${txtrst}

