#! /bin/bash

# Import color
source $AV_CONFIG_DIR/default_imports

# Check for a help flag
avCheckHelpFlags "$1" "builtin" "template script" "`$0 --help`"

# Import system path
avRestoreSystemPath

#### Put system commands here
$0 $*
#### End commands
