#! /bin/bash

export AV_OLD_SYSTEM_PATH=$PATH
export AV_PROJECT_CONFIG_DIR=$AV_ROOT/config
export AV_INSTALLED_BIN=$AV_INSTALLED_PATH/bin
export AV_INSTALLED_PLUGINS=$AV_INSTALLED_PATH/plugins/
export AV_CONFIG_DIR=$AV_INSTALLED_PATH/config
export AV_BIN_DIR=$AV_ROOT/bin
export AV_PROJ_TOP=$AV_ROOT/..

# Figure out OS
THIS_OS=`uname`

# Bring in color
source $AV_CONFIG_DIR/color

# Setup path
av_path="$AV_INSTALLED_BIN"
for plugin in `ls -1 $AV_INSTALLED_PLUGINS`; do
  av_path=${av_path}:$AV_INSTALLED_PLUGINS/${plugin}/bin
done

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace
TERM=xterm-color

# append to the history file, don't overwrite it
shopt -s histappend
shopt -s cdspell
shopt -s nocaseglob
 
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000
 
# Zsh style history search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac
 
# leave some commands out of history log
export HISTIGNORE="&:bg:fg:ll:h:??:[ ]*:clear:exit:logout"
export TIMEFORMAT=$'\nreal %3R\tuser %3U\tsys %3S\tpcpu %P\n'
export HISTTIMEFORMAT="%H:%M > "

# Make an alias so that help can run
alias help='$AV_INSTALLED_PATH/plugins/av-shell/bin/help'
alias team='$AV_INSTALLED_PATH/plugins/av-shell/bin/squad'
alias update='$AV_INSTALLED_PATH/plugins/av-shell/bin/upgrade'
alias get_tag_from_commit='$AV_INSTALLED_PATH/plugins/av-shell/bin/codehash'
alias sudo=`which sudo`
alias gawk=`which gawk`
alias awk=`which awk`
alias cat=`which cat`
alias less=`which less`
alias more=`which more`
alias sed=`which sed`
alias curl=`which curl`
alias wget=`which wget`
alias head=`which head`
alias tail=`which tail`
alias uniq=`which uniq`
alias grep=`which grep`
alias jq=`which jq`
alias ls=`whereis ls`
alias rm=`whereis rm`
alias node=`which node`
alias clear=`which clear`
alias git=`which git`
alias which=`which which`
alias mc=`which mc`
alias tree=`which tree`
alias pip=`which pip3`
alias python=`which python3`
alias vault=`which vault`


# OSX specific
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias sublime=`which sublime`
    alias subl=`which sublime`
    alias caffeinate=`which caffeinate`
fi

# Set prompt to something short and different
export PATH=$AV_BIN_DIR:${av_path}

function container_prompt() {
    cur_container=`getpv container`
    if [ ! -z ${cur_container} ]; then
        echo -e -n " [${cur_container}]"
    else
        echo -n ""
    fi
}

function cluster_prompt() {
    cur_cluster=`getpv cluster`
    if [ ! -z ${cur_cluster} ]; then
        echo -e -n " [${cur_cluster}]"
    else
        echo -n ""
    fi
}

function role_prompt() {
    cur_role=`getpv role`
    if [ ! -z ${cur_role} ]; then
        echo -e -n " [${cur_role}]"
    else
        echo -n ""
    fi
}

function topic_prompt() {
    cur_role=`getpv kafka-topic`
    if [ ! -z ${cur_role} ]; then
        echo -e -n " [${cur_role}]"
    else
        echo -n ""
    fi
}

# Welcome
if [[ "$AV_NON_INTERACTIVE" != "true" ]]; then
  export PROMPT=`/bin/cat $AV_PROJECT_CONFIG_DIR/prompt` 
  export PS1="\[${txtgrn}\]${PROMPT}\[${txtrst}\]\[${txtred}\]\$(cluster_prompt)\[${txtrst}\]\[${txtcyn}\]\$(container_prompt)\[${txtrst}\]\[${txtpur}\]\$(role_prompt)\[${txtrst}\]\[${txtpur}\]\$(topic_prompt)\[${txtrst}\]> "
  $AV_CONFIG_DIR/welcome
fi
