#! /bin/bash

# Import color
source $AV_CONFIG_DIR/default_imports

# Create root folder
containerdir=$(getpv containerdir)
if [[ -z ${containerdir} ]]; then
    cd $AV_ROOT/../ && mkdir -p containers
    containerdir="containers"
    echo "Containers will be stored in: ${containerdir}"
    setpv containerdir "containers"
fi

# Set docker repository
repo=$(getpv repo)
if [[ -z ${repo} ]]; then
    echo -n "What docker repository would you like to use: "
    read repo
    if [[ ! -z ${repo} ]]; then
        setpv repo ${repo}
    fi
else
    echo "Docker repository is setup at: ${repo}"
fi

# Copy a template docker container
templ_dir=$AV_INSTALLED_PLUGINS/av-stencil/docker-templates
templates=$(/bin/ls -1 ${templ_dir})

echo -e "Grab a sample container to start with..."
inquirer_menu container ${templates}
if [[ $? -eq 0 ]]; then
    sleep 1
    container=`getpv container`
    if [[ ! -z ${container} ]]; then
        
        echo -n "What would you like to name your container [${container}]: "
        read new_container
        if [[ -z ${new_container} ]]; then
            new_container=${container}
        fi
        /bin/cp -rv ${templ_dir}/${container} ${containerdir}/${new_container}
        setpv container ${new_container}
        echo
        echo -e "Edit your container via the files in ${containerdir}/${new_container}"
        echo -e "Now you can use docker commands within av-shell..."
        echo
    fi
fi
